# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Helena's Cleaning Service
email: info@helenascleaning.com
description: >- # this means to ignore newlines until "baseurl:"
  Helena's Cleaning Service, Inc. is a professional residential cleaning service with many years of experience.
  We have serviced the Chicagoland area for over 30 years.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://helenascleaning.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: helenascleaning
github_username:  gremz
phone_number: (630) 469-0216

google_analytics: UA-25276069-1

# Build settings
markdown: kramdown
theme: minima
sass:
  style: compressed
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
